// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/calendar": {
    params: {};
  };
  "/videos": {
    params: {};
  };
  "/videos/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/logout": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/dashboard" | "/chat" | "/calendar" | "/videos" | "/videos/:id" | "/profile" | "/settings" | "/logout";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/chat";
  };
  "routes/calendar.tsx": {
    id: "routes/calendar";
    page: "/calendar";
  };
  "routes/videos.tsx": {
    id: "routes/videos";
    page: "/videos";
  };
  "routes/videos.$id.tsx": {
    id: "routes/videos.$id";
    page: "/videos/:id";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/login": typeof import("./src/routes/login.tsx");
  "routes/register": typeof import("./src/routes/register.tsx");
  "routes/dashboard": typeof import("./src/routes/dashboard.tsx");
  "routes/chat": typeof import("./src/routes/chat.tsx");
  "routes/calendar": typeof import("./src/routes/calendar.tsx");
  "routes/videos": typeof import("./src/routes/videos.tsx");
  "routes/videos.$id": typeof import("./src/routes/videos.$id.tsx");
  "routes/profile": typeof import("./src/routes/profile.tsx");
  "routes/settings": typeof import("./src/routes/settings.tsx");
  "routes/logout": typeof import("./src/routes/logout.tsx");
};